# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cmaier/Hackerspaces/calliope/calliope-project-template/build/sinobit-classic-gcc-nosd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cmaier/Hackerspaces/calliope/calliope-project-template/build/sinobit-classic-gcc-nosd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmaier/Hackerspaces/calliope/calliope-project-template/build/sinobit-classic-gcc-nosd/CMakeFiles /home/cmaier/Hackerspaces/calliope/calliope-project-template/build/sinobit-classic-gcc-nosd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmaier/Hackerspaces/calliope/calliope-project-template/build/sinobit-classic-gcc-nosd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named all_tests

# Build rule for target.
all_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_tests
.PHONY : all_tests

# fast build rule for target.
all_tests/fast:
	$(MAKE) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/build
.PHONY : all_tests/fast

#=============================================================================
# Target rules for targets named mbed-classic

# Build rule for target.
mbed-classic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbed-classic
.PHONY : mbed-classic

# fast build rule for target.
mbed-classic/fast:
	$(MAKE) -f ym/mbed-classic/existing/CMakeFiles/mbed-classic.dir/build.make ym/mbed-classic/existing/CMakeFiles/mbed-classic.dir/build
.PHONY : mbed-classic/fast

#=============================================================================
# Target rules for targets named ble

# Build rule for target.
ble: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ble
.PHONY : ble

# fast build rule for target.
ble/fast:
	$(MAKE) -f ym/ble/source/CMakeFiles/ble.dir/build.make ym/ble/source/CMakeFiles/ble.dir/build
.PHONY : ble/fast

#=============================================================================
# Target rules for targets named ble-nrf51822

# Build rule for target.
ble-nrf51822: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ble-nrf51822
.PHONY : ble-nrf51822

# fast build rule for target.
ble-nrf51822/fast:
	$(MAKE) -f ym/ble-nrf51822/source/CMakeFiles/ble-nrf51822.dir/build.make ym/ble-nrf51822/source/CMakeFiles/ble-nrf51822.dir/build
.PHONY : ble-nrf51822/fast

#=============================================================================
# Target rules for targets named nrf51-sdk

# Build rule for target.
nrf51-sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrf51-sdk
.PHONY : nrf51-sdk

# fast build rule for target.
nrf51-sdk/fast:
	$(MAKE) -f ym/nrf51-sdk/source/CMakeFiles/nrf51-sdk.dir/build.make ym/nrf51-sdk/source/CMakeFiles/nrf51-sdk.dir/build
.PHONY : nrf51-sdk/fast

#=============================================================================
# Target rules for targets named microbit-dal

# Build rule for target.
microbit-dal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 microbit-dal
.PHONY : microbit-dal

# fast build rule for target.
microbit-dal/fast:
	$(MAKE) -f ym/microbit-dal/source/CMakeFiles/microbit-dal.dir/build.make ym/microbit-dal/source/CMakeFiles/microbit-dal.dir/build
.PHONY : microbit-dal/fast

#=============================================================================
# Target rules for targets named microbit

# Build rule for target.
microbit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 microbit
.PHONY : microbit

# fast build rule for target.
microbit/fast:
	$(MAKE) -f ym/microbit/source/CMakeFiles/microbit.dir/build.make ym/microbit/source/CMakeFiles/microbit.dir/build
.PHONY : microbit/fast

#=============================================================================
# Target rules for targets named sinobit-project-template

# Build rule for target.
sinobit-project-template: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sinobit-project-template
.PHONY : sinobit-project-template

# fast build rule for target.
sinobit-project-template/fast:
	$(MAKE) -f source/CMakeFiles/sinobit-project-template.dir/build.make source/CMakeFiles/sinobit-project-template.dir/build
.PHONY : sinobit-project-template/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... all_tests"
	@echo "... mbed-classic"
	@echo "... ble"
	@echo "... ble-nrf51822"
	@echo "... nrf51-sdk"
	@echo "... microbit-dal"
	@echo "... microbit"
	@echo "... sinobit-project-template"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

