#ifndef __YOTTA_CONFIG_H__
#define __YOTTA_CONFIG_H__
// yotta config data (including backwards-compatible definitions)
#define TARGET CALLIOPE_MINI_CLASSIC_GCC_NOSD
#define TARGET_LIKE_CALLIOPE_MINI_CLASSIC_GCC_NOSD
#define YOTTA_BUILD_INFO_HEADER "/home/cmaier/Hackerspaces/calliope/calliope-project-template/build/calliope-mini-classic-gcc-nosd/yotta_build_info.h"
#define TARGET_LIKE_CALLIOPE_MINI_CLASSIC_GCC_NOSD
#define TARGET_LIKE_NRF51822
#define TARGET_LIKE_NRF
#define TARGET_LIKE_NORDIC
#define TARGET_LIKE_CORTEX_M0
#define TARGET_LIKE_ARMV6_M
#define TARGET_LIKE_MBED_CLASSIC
#define TARGET_LIKE_CALLIOPE
#define TARGET_LIKE_MBED_GCC
#define TARGET_LIKE_MBED
#define TARGET_LIKE_ARM
#define TARGET_LIKE_GCC
#define YOTTA_CFG
#define YOTTA_CFG_MINAR
#define YOTTA_CFG_MINAR_INITIAL_EVENT_POOL_SIZE 50
#define YOTTA_CFG_MINAR_ADDITIONAL_EVENT_POOLS_SIZE 100
#define YOTTA_CFG_ARCH
#define YOTTA_CFG_ARCH_ARM
#define YOTTA_CFG_MICROBIT_DAL
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH
#define YOTTA_CFG_MICROBIT_DAL_BLUETOOTH_ENABLED 0
#define YOTTA_CFG_MICROBIT_DAL_DEBUG 1
#define YOTTA_CFG_MBED

// version definitions
#define YOTTA_MICROBIT_VERSION_STRING "2.0.0-rc8-calliope-1.0.3"
#define YOTTA_MICROBIT_VERSION_MAJOR 2
#define YOTTA_MICROBIT_VERSION_MINOR 0
#define YOTTA_MICROBIT_VERSION_PATCH 0
#define YOTTA_MICROBIT_DAL_VERSION_STRING "2.0.0-rc8-calliope-1.0.3"
#define YOTTA_MICROBIT_DAL_VERSION_MAJOR 2
#define YOTTA_MICROBIT_DAL_VERSION_MINOR 0
#define YOTTA_MICROBIT_DAL_VERSION_PATCH 0
#define YOTTA_MBED_CLASSIC_VERSION_STRING "0.0.5"
#define YOTTA_MBED_CLASSIC_VERSION_MAJOR 0
#define YOTTA_MBED_CLASSIC_VERSION_MINOR 0
#define YOTTA_MBED_CLASSIC_VERSION_PATCH 5
#define YOTTA_BLE_VERSION_STRING "2.5.0"
#define YOTTA_BLE_VERSION_MAJOR 2
#define YOTTA_BLE_VERSION_MINOR 5
#define YOTTA_BLE_VERSION_PATCH 0
#define YOTTA_BLE_NRF51822_VERSION_STRING "2.5.0"
#define YOTTA_BLE_NRF51822_VERSION_MAJOR 2
#define YOTTA_BLE_NRF51822_VERSION_MINOR 5
#define YOTTA_BLE_NRF51822_VERSION_PATCH 0
#define YOTTA_NRF51_SDK_VERSION_STRING "2.2.0"
#define YOTTA_NRF51_SDK_VERSION_MAJOR 2
#define YOTTA_NRF51_SDK_VERSION_MINOR 2
#define YOTTA_NRF51_SDK_VERSION_PATCH 0
#define YOTTA_CALLIOPE_PROJECT_TEMPLATE_VERSION_STRING "1.0.0"
#define YOTTA_CALLIOPE_PROJECT_TEMPLATE_VERSION_MAJOR 1
#define YOTTA_CALLIOPE_PROJECT_TEMPLATE_VERSION_MINOR 0
#define YOTTA_CALLIOPE_PROJECT_TEMPLATE_VERSION_PATCH 0
#endif // ndef __YOTTA_CONFIG_H__
