# NOTE: This file is generated by yotta: changes will be overwritten!

if(YOTTA_META_TOOLCHAIN_FILE_INCLUDED)
    return()
endif()
set(YOTTA_META_TOOLCHAIN_FILE_INCLUDED 1)

include("/home/cmaier/Hackerspaces/calliope/calliope-project-template/yotta_targets/mbed-gcc/CMake/toolchain.cmake")
include("/home/cmaier/Hackerspaces/calliope/calliope-project-template/yotta_targets/calliope-mini-classic-gcc-nosd/CMake/toolchain.cmake")
